# Generated by Django 4.2 on 2024-04-11 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Описание задачи')),
                ('urgency', models.BooleanField(default=True, verbose_name='Срочность задачи')),
                ('importancy', models.BooleanField(default=True, verbose_name='Важность задачи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна ли задача')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец задачи')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'task',
                'ordering': ('id',),
            },
        ),
    ]
